FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

RUN apk add --no-cache maven

COPY apps/payment-service/pom.xml .
RUN mvn dependency:go-offline

COPY apps/payment-service/src ./src

EXPOSE 8080

CMD ["mvn", "spring-boot:run"]
