FROM golang:1.21-alpine

RUN apk add --no-cache git ca-certificates

WORKDIR /app

COPY libs/kafka-clients/go /libs/kafka-clients/go
COPY apps/order-service/go.mod apps/order-service/go.sum ./
RUN go mod download

COPY apps/order-service/ .

RUN go build -o order-service .

EXPOSE 8080

CMD ["./order-service"]
